spring.application.name=feedback_action_tracker_api

spring.datasource.url=jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# --- JPA/Hibernate ---
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true

# --- Flyway config ---
spring.flyway.enabled=true
spring.flyway.locations=classpath:db/migration